Jd/retry intents
0xsequence/sequence-unreal pull request #203
Opened 2024-10-21 20:22 UTC by ZemindJan

2024-10-22 14:29 UTC, BellringerQuinn requested changes

2024-10-22 16:14 UTC, BellringerQuinn approved these changes
Thank you! This will resolve a pesky integration/user issue that comes up now and then

2024-10-24 16:18 UTC, colezemind requested changes

2024-10-28 17:01 UTC, colezemind approved these changes
Looks good!

2024-11-04 20:37 UTC, colezemind commented on Plugins/SequencePlugin/Source/SequencePlugin/Private/RequestHandler.cpp
> +				OnFailure(FSequenceError(RequestFail, "Request is invalid" + Response->GetContentAsString()));
This line may be referencing Response when Response isn't valid

2024-11-04 20:39 UTC, colezemind reviewed
Just one change request required, looks like a response may have been getting referenced when it was invalid

2024-11-04 20:46 UTC, colezemind approved these changes
Changes look good!

2024-11-04 20:46 UTC, merged