228 marketplace reader support
0xsequence/sequence-unreal pull request #263
Opened 2024-12-17 14:53 UTC by ZemindJan

2025-03-07 21:23 UTC, BellringerQuinn requested changes

2025-03-07 21:23 UTC, BellringerQuinn commented on Plugins/SequenceTests/Source/SequenceTests/Private/IndexerEndToEndTests/Helpers/IndexerEndToEndTestsCommon.h
> +namespace MarketplaceEndToEndTestsCommon
Why?

2025-03-07 21:23 UTC, BellringerQuinn commented on Plugins/SequenceTests/Source/SequenceTests/Private/MarketplaceEndToEndTests/Helpers/IndexerEndToEndTestsCommon.h
Ahh, I think I see what happened above - copy/paste error 😄 

Wrong file name here

2025-03-07 21:23 UTC, BellringerQuinn commented on Plugins/SequencePlugin/Source/SequencePlugin/Public/Marketplace/Structs/SeqCurrency.h
> +	int ID;
Hmm... I'm not sure if the id's are parsing properly. When I run the test I see all the id's are 0

{
    "iD": 0,
    "chainId": 137,
    ...
}

The are more fields that can be added as well, see [Unity code](https://github.com/0xsequence/sequence-unity/blob/Feature/marketplaceCheckout/Packages/Sequence-Unity/Sequence/SequenceSDK/Marketplace/DataTypes/Currency.cs) as an example, we can add them now or in a later ticket/pr

2025-05-20 12:20 UTC, andygruening commented
Closing because this was already merged into v2

2025-05-20 12:20 UTC, closed without merging